### PR TITLE
Also can use PascalCase for modules

### PR DESCRIPTION
**Pull request by jansepar**
Status: **Opened for visibility**

Reviewers: Any Mobify engineer!

## Changes
- Allow the use of PascalCase for modules

### CODE REVIEW

**Comment by tedtate** [comment]
:+1:

**Comment by ry5n** [comment]
Is there a precedent for PascalCase modules?

**Comment by tedtate** [comment]
@ry5n precedent in our code? I think for the most part this is the standard that we use, we are just codifying it officially here.

**Comment by ry5n** [comment]
I mean precedent in the JS community. I’m not the best person to critique the decision, but if this is a Mobify-specific idiom I’m not sure it’s a great idea: it could confuse people used to the “normal” meaning of PascalCase.

**Comment by tedtate** [comment]
I've seen it written both ways. In many cases modules are really more like namespaces where I think the leading upper-case is a nice.

**Comment by ry5n** [comment]
Thanks, good to know.

**Pull request merged**
