### PR TITLE
Remove rule preventing extra parens

### PR DESCRIPTION
**Pull request by MikeKlemarewski**
Up for debate!

### CODE REVIEW

**Comment by ry5n** [comment]
+1

**Comment by marlowpayne** [comment]
Rule doc [here](http://eslint.org/docs/rules/no-extra-parens)

Maybe we should set the rule to `functions`, so function expressions will still be checked for extra parens?
e.g. `((function foo() {}))();`

**Comment by haroldtreen** [comment]
Ya, I think the functions case is still good. The times this rule has tripped me has only been in expressions.

**Comment by MikeKlemarewski** [comment]
@marlowpayne I like that idea. How do I set it to still check functions?

**Comment by marlowpayne** [comment]
@MikeKlemarewski `"no-extra-parens": [2, "functions"]`

**Comment by marlowpayne** [comment]
:+1:

**Pull request merged**
