### PR TITLE
Add CSSComb

### PR DESCRIPTION
**Pull request by jeffkamo**
Status: **Ready for Review** or **WIP**
Owner: @jeffkamo
Reviewers: @bengroulx @cole-sanderson @mlworks @yourpalsonja @vivchen @ry5n

## Changes
- Add CSSComb config

## Todos:
- [x] A bunch of +1's

### CODE REVIEW

**Comment by mediumjones** [comment]
👍

**Comment by mediumjones** [comment]
+1

**Comment by ry5n** [comment]
+1

**Comment by yourpalsonja** [comment]
:spaghetti: 1

**Comment by jeffkamo** [comment]
Thanks folks! At long, long last, CSSComb has arrived!

**Pull request merged**
