### PR TITLE
Add new class and CSS conventions

### PR DESCRIPTION
**Pull request by jeffkamo**
Status: **Ready for Review**
Owner: @jeffkamo
Reviewers: @kpeatt @ry5n @avelinet @nastiatikk @cole-sanderson @mlworks

## Changes
- Add "don't style `js-` classes" to the [class prefix convention table](https://github.com/mobify/mobify-code-style/tree/master/css/class-naming-conventions#class-prefix-conventions)
- modify `x-` description in the [class prefix convention table](https://github.com/mobify/mobify-code-style/tree/master/css/class-naming-conventions#class-prefix-conventions) to reflect it's new role (global/document states)
- Add "kebab-case" to class convention
- Add a section discussing context sensitive styles, i.e. how to declare `absolute` positions in context

## Todos:
- [x] Developer +1
- [x] Another Developer +1
- [x] @kpeatt's loving approval

### Feedback:
_none so far_

### CODE REVIEW

**Comment by nastiatikk** [comment]
Add extending order?
```
.c-component.c--modifier,
%c-component--modifier
```

**Comment by ry5n** [comment]
+1. One nit: probably best to put deprecated stuff at the bottom of lists (in this case, `m-` classes after `.js-` classes.

**Comment by kpeatt** [comment]
> UPD: I thought it's a general Code Style update. Should this suggestion be in another PR then?

Yep, another PR would be great!

**Comment by jeffkamo** [comment]
@mlworks @cole-sanderson @yourpalsonja @bengroulx @vivchen @ry5n @zacharyhalvorson 

Is anyone opposed to me merging this PR?

**Comment by yourpalsonja** [comment]
Not 1! +1 +1

**Comment by kpeatt** [comment]
:ship:

**Comment by jeffkamo** [comment]
(awthanks) @kpeatt!

**Pull request merged**
