### PR TITLE
Fix lint/comb rule to support both single and double quotes

### PR DESCRIPTION
**Pull request by jeffkamo**
@marlowpayne

At Mobify, we most commonly use both double quotes and single quotes in our CSS. We want to support both!

## Todo

- [x] Figure out how to disable quotes

### CODE REVIEW

**Comment by jeffkamo** [comment]
There's a problem: CSScomb doesn't have a way to disable single quotes...

We actually want to support both single and double quotes, but CSScomb won't let us :(

**Comment by marlowpayne** [comment]
Booo! :ghost:

**Comment by jeffkamo** [comment]
Nevermind! We can set the rule to `false` and that works.

**Comment by marlowpayne** [comment]
Looking good! :+1:

**Pull request merged**
