### PR TITLE
🎨 Update eslint plugin settings asset

### PR DESCRIPTION
**Pull request by marlowpayne**
## Changes
- Update the asset that shows the eslint Atom plugin settings

## How To Test
- Take a look at the new asset
  - See it in context [here](https://github.com/mobify/mobify-code-style/blob/f73251da293fbf7ecd851bf73f4e023a9d016f58/javascript/atom.md)

## TODOs:
- [x] +1
- [x] Updated README
- [x] ~~Updated CHANGELOG~~

### CODE REVIEW

**Comment by kschmidtdev** [comment]
Which version of `linter-eslint` are you running? I have `8.0.0` but I don't have the `Eslint Path` field?

**Comment by marlowpayne** [comment]
@kschmidtdev interesting... I'm also running `8.0.0`.

screen shot 2016-11-24 at 11 23 16 am

**Comment by kschmidtdev** [comment]
I guess we must have different situations re: 

screen shot 2016-11-24 at 11 31 23 am

**Comment by kschmidtdev** [comment]
👍

**Pull request merged**
