### PR TITLE
Self Documenting Selectors Update

### PR DESCRIPTION
**Pull request by yourpalsonja**
Status: **Ready for Review**
Owner: @yourpalsonja
Reviewers: @ry5n @avelinet @nastiatikk @cole-sanderson @mlworks @jeffkamo

## Changes
- Added in a missing semi-colon. Things make so much more sense now. Thanks @nastiatikk for the find.

## Todos:
- [x] Designer/Developer +1 @jeffkamo
- [x] Designer/Developer +1 @ry5n

### Feedback:
_none so far_

### CODE REVIEW

**Comment by jeffkamo** [comment]
+1

**Comment by ry5n** [comment]
+1

**Comment by ry5n** [comment]
Merge away!

**Comment by yourpalsonja** [comment]
:joy_cat:

**Pull request merged**
